version: '3'
services:
    php:
        image: php:7.4-apache
        restart: always
        depends_on:
            database:
                condition: service_healthy
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - .:${APACHE_DOCUMENT_ROOT}
        working_dir: "${APACHE_DOCUMENT_ROOT}"
        ports:
            - '${APACHE_PORT}:80'
        links:
            - "database:db"
        entrypoint: [ "/bin/sh", "-c" ]
        command:
            - |
                source ./docker/php/init.sh
                php artisan migrate:fresh --seed
                php artisan storage:link
                chmod o+w ./storage/ -R
                apachectl -D FOREGROUND
    nodejs:
        image: node:16.13.2
        volumes:
            - .:/blood-cancer-management-platform
        working_dir: '/blood-cancer-management-platform'
        entrypoint: [ "/bin/sh", "-c" ]
        command:
            - |
                npm install
                npm run dev
    composer:
        image: composer:2.2.5
        volumes:
            - .:/code
        working_dir: '/code'
        entrypoint: [ "/bin/sh", "-c" ]
        command:
            - |
                composer install --ignore-platform-reqs
    database:
        image: mariadb:10.5.10
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        expose:
            - '3306'
        volumes:
            - "./docker/mariadb/ddl.sql:/docker-entrypoint-initdb.d/1.sql"
            - "./docker/mariadb/mariadb.cnf:/etc/mysql/conf.d/mariadb.cnf"
            - /etc/localtime:/etc/localtime:ro
        command:
            - mysqld
            - --character-set-server=utf8
            - --collation-server=utf8_general_ci
        healthcheck:
            test: "exit 0"
