version: '3'
services:
    php:
        image: php:7.4-apache
        restart: always
        depends_on:
            database:
                condition: service_healthy
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - .:/var/www/html
        working_dir: "/var/www/html"
        ports:
            - '20020:80'
        links:
            - "database:db"
        env_file:
            - ./docker/config.env
        entrypoint: [ "/bin/sh", "-c" ]
        command:
            - |
                docker-php-ext-configure pdo_mysql && docker-php-ext-install pdo_mysql
                ln -s /etc/apache2/mods-available/rewrite.load /etc/apache2/mods-enabled/rewrite.load
                sed -ri -e 's!/var/www/html!/var/www/html/public!g' /etc/apache2/sites-available/*.conf
                sed -ri -e 's!/var/www/!/var/www/html/public!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf
                sed -i '/<Directory \/var\/www\/html\/public>/,/<\/Directory>/ s/AllowOverride None/AllowOverride all/' /etc/apache2/apache2.conf
                php artisan migrate:fresh --seed
                php artisan storage:link
                apachectl -D FOREGROUND
    nodejs:
        image: node:16.13.2
        volumes:
            - .:/blood-cancer-management-platform
        working_dir: '/blood-cancer-management-platform'
        entrypoint: [ "/bin/sh", "-c" ]
        command:
            - |
                npm install
                npm run dev
    composer:
        image: composer:2.2.5
        volumes:
            - .:/code
        working_dir: '/code'
        entrypoint: [ "/bin/sh", "-c" ]
        command:
            - |
                composer install --ignore-platform-reqs
    database:
        image: mariadb:10.5.10
        restart: always
        expose:
            - '3306'
        volumes:
            - "./docker/mariadb/ddl.sql:/docker-entrypoint-initdb.d/1.sql"
            - "./docker/mariadb/mariadb.cnf:/etc/mysql/conf.d/mariadb.cnf"
            - /etc/localtime:/etc/localtime:ro
        env_file:
            - ./docker/config.env
        command:
            - mysqld
            - --character-set-server=utf8
            - --collation-server=utf8_general_ci
        healthcheck:
            test: "exit 0"
